title: Porter Bagley
logo: "/images/DaybreakHeadshotCircle.png?raw=true
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate about applying data science to real world problems
  <br><br>
  <a href="https://www.linkedin.com/in/porter-bagley/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
